apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      serviceAccountName: argo
      containers:
      - name: workflow-controller
        image: argoproj/workflow-controller:v2.8.1-artifact-permissions
        command:
        - workflow-controller
        args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - argoproj/argoexec:v2.8.1-artifact-permissions
      nodeSelector:
        kubernetes.io/os: linux
